### ISSUE TITLE
Adopt rustfmt to keep code formatting

### ISSUE THREAD

**Issue by hyunsik** [hyunsik/tokamak#10]
It would be very helpful to keep coding standard for us.
https://github.com/rust-lang-nursery/rustfmt

**Comment by jihoonson** [comment]
+1. It looks nice to me.

**Comment by jihoonson** [comment]
The default tab width is 4, so we need to set as 2. Also, ```reorder_imports``` looks useful. 
Do you have any further requirements?

**Comment by hyunsik** [comment]
I also think that two rules would be enough and simple to keep them.

Currently, I'm writing a script to reformat every sub crates in Tokamak root. With this script, I'll commit it soon.

**Comment by jihoonson** [comment]
Sounds great.
I hope to set ```wrap_comments``` additionally. We can automatically wrap too long comments as well.

**Comment by hyunsik** [comment]
Thank you for your suggestion. I applied ``wrap_comments`` too.

**Comment by hyunsik** [comment]
code changes in some modules are required by rustfmt. So, I resolved them and commit each module.

**Comment by jihoonson** [comment]
Looks great. Thanks!
